In [45]:
import nltk
import numpy as np
from textblob import TextBlob

In [46]:
text = ["wookie stormtrooper",
        "wookie wookie wookie stormtrooper stormtrooper stormtrooper",
        "harry potter"]
vect = CountVectorizer()
data = vect.fit_transform(text).todense()

In [47]:
#Bag of words approach, kinda like naive bayes
print(vect.get_feature_names())
print(data)

['harry', 'potter', 'stormtrooper', 'wookie']
[[0 0 1 1]
 [0 0 3 3]
 [1 1 0 0]]


In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances, pairwise_distances

In [49]:
print(pairwise_distances(data, metric = 'euclidean'))

[[0.         2.82842712 2.        ]
 [2.82842712 0.         4.47213595]
 [2.         4.47213595 0.        ]]


In [50]:
print(pairwise_distances(data, metric = 'cosine'))
#cosine distance is compliment of cosine similarity
#if a document is simliar, we hope to see 0
#cosine is a good metric for documents

[[0. 0. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


In [51]:
print(np.corrcoef(data))
# 1 is correlated, -1 is not correlation

[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [-1. -1.  1.]]


In [52]:
# Vectorise the data
vec = TfidfVectorizer()
X = vec.fit_transform(text) # `X` will now be a TF-IDF representation of the data, the first row of `X` corresponds to the first sentence in `data`

# Calculate the pairwise cosine similarities (depending on the amount of data that you are going to have this could take a while)
S = cosine_similarity(data)
E = euclidean_distances(data)

In [53]:
S

array([[1., 1., 0.],
       [1., 1., 0.],
       [0., 0., 1.]])

In [41]:
E

array([[0.        , 2.82842712, 2.        ],
       [2.82842712, 0.        , 4.47213595],
       [2.        , 4.47213595, 0.        ]])

In [34]:
X

<3x4 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>